carshop/Controllers/carsController.cs
using carshop.DBCommunicating;
using Microsoft.AspNetCore.Mvc;

namespace carshop.Controllers {
    public class carsController : Controller {
        private readonly UserCommunicating userComm = new();

        public ViewResult List() {
            return View("Pages/Cars/List.cshtml", userComm.AllCars());
        }
        public ViewResult AddCar() {
            return View("Pages/Cars/AddCar.cshtml");
        }
        public ViewResult OpResult(string Mail, string Password, string Brand, string Body, decimal Price, Data.CarType Type) {
            bool result = userComm.AddCarToList(new Data.CarOwner("temp", Mail, Password), new Data.Car(Brand, Body, Price, Type));

            return View("Pages/Cars/OpResult.cshtml", Convert.ToInt32(result));
        }
    }
}

carshop/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace carshop.Pages {
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger) {
            _logger = logger;
        }

        public void OnGet() {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

carshop/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace carshop.Pages {
    public class IndexModel : PageModel {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger) {
            _logger = logger;
        }

        public void OnGet() {

        }
    }
}

carshop/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace carshop.Pages {
    public class PrivacyModel : PageModel {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger) {
            _logger = logger;
        }

        public void OnGet() {
        }
    }

}

carshop/Pages/Cars/AddCar.cshtml
@using (Html.BeginForm("opresult", "cars", FormMethod.Post)) {
    <div class="form-group">
        <label for="Mail">Mail:</label>
        <input type="email" name="Mail" id="Mail" class="form-control" />
    </div>

    <div class="form-group">
        <label for="Password">Password:</label>
        <input type="password" name="Password" id="Password" class="form-control" />
    </div>


    <div class="form-group">
        <label for="name">Brand:</label>
        <input type="text" name="Brand" id="Brand" class="form-control" />
    </div>

    <div class="form-group">
        <label for="Body">Body:</label>
        <input type="text" name="Body" id="Body" class="form-control" />
    </div>

    <div class="form-group">
        <label for="Type">Type:</label>
        <select name="Type" id="Type" class="form-control">
            <option value="Jeep">Jeep</option>
            <option value="Truck">Truck</option>
            <option value="Sedan">Sedan</option>
        </select>
    </div>

    <div class="form-group">
        <label for="Price">Price:</label>
        <input type="text" name="Price" id="Price" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary">Отправить</button>
}

carshop/Pages/Cars/List.cshtml
<h1>Все автомобили:</h1>
@{
    foreach(var car in Model) {
        <div>
            <h2>Марка: @car.Brand</h2>
            <p>Цена: @car.Price.ToString("c")</p>
            <p>Владелец: @car.OwnerNickname</p>
        </div>
    }
}

carshop/Pages/Cars/OpResult.cshtml
<html>
@{
    if (Model is 1) {
        <head>
            <title>Успех</title>
        </head>
        <body>
            <div>
                <h1>Объявление было успешно добавлено!</h1>
            </div>
        </body>
    } else {
        <head>
            <title>Ошибка</title>
        </head>
        <body>
            <div>
                <h1>Что-то пошло не так!</h1>
            </div>
        </body>
    }
}

</html>

carshop/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

carshop/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - carshop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/carshop.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">carshop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - carshop - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>